### ISSUE TITLE
画像分類器にエラー

### ISSUE THREAD

**Issue by camberbridge** [egroup-develop/sandbox#13]
参考ページ(http://qiita.com/CORDEA/items/9fad27ae024928b6a7b1)の
「リファレンスモデルでの分類」を行っていて、
caffe/pythonのディレクトリで、
python classify.py --raw_scale 255 ../101_ObjectCategories/airplanes/image_0001.jpg ../result.npy
を実行したときに、下記のエラーが出てきます

Traceback (most recent call last): 
 File "classify.py", line 138, in <module> 
 main(sys.argv) File "classify.py", line 110, in main channel_swap=channel_swap) 
 File "/root/caffe/python/caffe/classifier.py", line 26, in **init** 
 caffe.Net.**init**(self, model_file, pretrained_file, caffe.TEST)
RuntimeError: Could not open file ../models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
- 追記: 解決しました
  ../models/bvlc_reference_caffenet/で
  wget http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodelで解決しました

**Comment by camberbridge** [comment]
リファレンスモデルを使った飛行機や猫等の画像分類はできた！！
