### ISSUE TITLE
caffeでのエラー

### ISSUE THREAD

**Issue by camberbridge** [egroup-develop/sandbox#14]
[参考](http://techblog.yahoo.co.jp/programming/caffe-intro/)にならい, Caffeを特徴器として使った分類を試みております.
特徴抽出の節で示されている方法通りに
$ python feature.py 101_ObjectCategories/airplanes/image_0001.jpg
を実行して画像(image_0001.jpg)の特徴量を計算させると下記のエラーが出ます.

Traceback (most recent call last):
  File "feature.py", line 12, in <module>
    net = caffe.Classifier(MODEL_FILE, PRETRAINED)
  File "/root/caffe/python/caffe/classifier.py", line 26, in **init**
    caffe.Net.**init**(self, model_file, pretrained_file, caffe.TEST)
MemoryError

メモリエラーとのことですが, Docker固有の問題でしょうか. いろいろ試してみましたが依然としてMemorryErrorは消えません. 
お力添えいただけますよう, よろしくお願いいたします.

**Comment by camberbridge** [comment]
解決) vmインスタンスのメモリを3 GBほどにして作り直して挑戦したところ無事に処理が通った
